import type { Provider } from "../types/provider.types";

export const PROVIDERS: Provider[] = [
    {
        id: "iyzico",
        name: "iyzico",
        subtitle: "PayU iştirakidir",
        logo: "/logos/iyzico.png",
        commissionRate: { min: 2.99, max: null },
        installmentRates: { 3: 5.49, 6: 8.99, 12: 14.50 },
        paymentSpeed: "Haftalık",
        paymentSpeedHours: 168,
        features: ["Pazar Yeri", "Korumalı Alışveriş", "Sanal POS", "Dövizle Ödeme"],
        currencyRates: {
            USD: 2.99,
            EUR: 2.89
        },
        isPopular: true,
        segment: "her ikisi",
        applyUrl: "https://iyzico.com",
        rating: 4.5,
        reviewCount: 1240,
        description:
            "Türkiye'nin en büyük ödeme altyapı şirketi. PayU iştirakı olan iyzico, 200.000'den fazla üye iş yerinde hizmet vermektedir. Gelişmiş fraud koruması, pazar yeri çözümü ve çoklu para birimi desteği ile e-ticaret altyapınızı güçlendirin.",
        monthlyFee: null,
        setupFee: null,
        fixedFee: 0.25,
    },
    {
        id: "paytr",
        name: "PayTR",
        subtitle: "Yerli ve Güçlü",
        logo: "/logos/paytr.png",
        commissionRate: { min: 2.49, max: null },
        installmentRates: { 3: 4.99, 6: 7.49, 12: 12.90 },
        paymentSpeed: "Ertesi Gün",
        paymentSpeedHours: 24,
        features: ["Linkle Ödeme", "Fiziki POS", "Sanal POS", "Dövizle Ödeme"],
        currencyRates: {
            USD: 2.49,
            EUR: 2.39,
            GBP: 2.59
        },
        cryptoRates: {
            USDT: 1.99
        },
        isPopular: true,
        segment: "her ikisi",
        applyUrl: "https://paytr.com",
        rating: 4.3,
        reviewCount: 890,
        description:
            "PayTR, hızlı ödeme ve düşük komisyon oranlarıyla öne çıkan yerli ödeme çözümüdür. Linkle ödeme, QR kod ve mobil ödeme seçenekleri ile müşterilerinize çok kanallı ödeme deneyimi sunun.",
        monthlyFee: null,
        setupFee: null,
        fixedFee: 0.00,
    },
    {
        id: "param",
        name: "Param",
        subtitle: "Kapsamlı Çözümler",
        logo: "/logos/param.png",
        commissionRate: { min: 1.99, max: null },
        installmentRates: { 3: 4.50, 6: 7.90, 12: 13.50 },
        paymentSpeed: "Anında",
        paymentSpeedHours: 0,
        features: ["Fiziki Kart Avantajı", "Anlık Transfer", "7/24 Destek"],
        isPopular: false,
        segment: "her ikisi",
        applyUrl: "https://param.com.tr",
        rating: 4.1,
        reviewCount: 620,
        description:
            "Param, fiziki kart avantajı ile hem online hem offline ödeme çözümü sunan kapsamlı bir platformdur. Anlık transfer ve 7/24 müşteri desteği ile kesintisiz ödeme deneyimi sağlayın.",
        monthlyFee: null,
        setupFee: null,
        fixedFee: 0.15,
    },
    {
        id: "sipay",
        name: "Sipay",
        subtitle: "Dijital Cüzdan",
        logo: "/logos/sipay.png",
        commissionRate: { min: 2.29, max: null },
        installmentRates: { 3: 5.10, 6: 8.20, 12: 14.00 },
        paymentSpeed: "Ertesi Gün",
        paymentSpeedHours: 24,
        features: ["Dijital Cüzdan", "Taksitli Ödeme", "API Entegrasyonu"],
        isPopular: false,
        segment: "her ikisi",
        applyUrl: "https://sipay.com.tr",
        rating: 4.0,
        reviewCount: 430,
        description:
            "Sipay, dijital cüzdan teknolojisi ve taksitli ödeme seçenekleriyle modern ödeme deneyimi sunan yenilikçi bir platformdur.",
        monthlyFee: null,
        setupFee: null,
        fixedFee: 0.00,
    },
    {
        id: "craftgate",
        name: "Craftgate",
        subtitle: "Geliştirici Dostu",
        logo: "/logos/craftgate.png",
        commissionRate: { min: 2.79, max: null },
        installmentRates: { 3: 5.25, 6: 8.50, 12: 13.75 },
        paymentSpeed: "Ertesi Gün",
        paymentSpeedHours: 24,
        features: ["Fiziki Kart", "Sanal POS", "Cüzdan"],
        currencyRates: {
            EUR: 2.75
        },
        cryptoRates: {
            USDT: 2.10
        },
        isPopular: false,
        segment: "kurumsal",
        applyUrl: "https://craftgate.io",
        rating: 4.6,
        reviewCount: 310,
        description:
            "Craftgate, geliştiriciler için tasarlanmış modern ödeme orkestrasyon platformudur. Sandbox ortamı, detaylı API dokümantasyonu ve webhook desteğiyle entegrasyon süreçlerinizi hızlandırın.",
        monthlyFee: null,
        setupFee: null,
        fixedFee: 0.50,
    },
    {
        id: "moka",
        name: "Moka",
        subtitle: "Kolay Entegrasyon",
        logo: "/logos/moka.png",
        commissionRate: { min: 2.69, max: null },
        installmentRates: { 3: 5.35, 6: 8.75, 12: 14.90 },
        paymentSpeed: "Ertesi Gün",
        paymentSpeedHours: 24,
        features: ["Kolay Entegrasyon", "Abonelik Yönetimi", "Raporlama"],
        isPopular: false,
        segment: "her ikisi",
        applyUrl: "https://moka.com",
        rating: 4.2,
        reviewCount: 560,
        description:
            "Moka, kolay entegrasyon ve kapsamlı raporlama özellikleriyle öne çıkan ödeme çözümüdür. Abonelik yönetimi ile tekrarlayan ödemeleri kolayca yönetin.",
        monthlyFee: null,
        setupFee: null,
        fixedFee: 0.20,
    },
];
