import type { Review } from "../types/review.types";

export const REVIEWS: Review[] = [
    {
        id: "r1",
        providerId: "iyzico",
        userName: "Ahmet Y.",
        rating: 5,
        comment: "Entegrasyonu çok kolay, dokümantasyonları harika. Pazar yeri çözümü işimize çok yaradı.",
        date: "2026-01-15",
    },
    {
        id: "r2",
        providerId: "iyzico",
        userName: "Elif K.",
        rating: 4,
        comment: "Genel olarak memnunum fakat komisyon oranları biraz yüksek. Müşteri desteği hızlı.",
        date: "2026-01-02",
    },
    {
        id: "r3",
        providerId: "paytr",
        userName: "Mehmet A.",
        rating: 5,
        comment: "2 saat içinde ödeme gerçekten çalışıyor. Nakit akışı açısından büyük avantaj.",
        date: "2026-01-20",
    },
    {
        id: "r4",
        providerId: "paytr",
        userName: "Zeynep D.",
        rating: 4,
        comment: "QR kod ödeme özelliğini çok beğendik. Fiziki mağazamız için de kullanıyoruz.",
        date: "2025-12-28",
    },
    {
        id: "r5",
        providerId: "param",
        userName: "Can Ö.",
        rating: 4,
        comment: "Anlık transfer çok yardımcı oluyor. Destek ekibi 7/24 gerçekten ulaşılabilir.",
        date: "2026-01-10",
    },
    {
        id: "r6",
        providerId: "param",
        userName: "Selin T.",
        rating: 5,
        comment: "En düşük komisyon oranını Param'da bulduk. Fiziki kart avantajı da cabası.",
        date: "2026-02-01",
    },
    {
        id: "r7",
        providerId: "sipay",
        userName: "Burak M.",
        rating: 4,
        comment: "Dijital cüzdan özelliği müşterilerimiz tarafından çok beğeniliyor. Taksit seçenekleri geniş.",
        date: "2026-01-25",
    },
    {
        id: "r8",
        providerId: "craftgate",
        userName: "Deniz S.",
        rating: 5,
        comment: "Geliştirici olarak en iyi deneyimi Craftgate'te yaşadım. Sandbox ortamı mükemmel.",
        date: "2026-01-18",
    },
    {
        id: "r9",
        providerId: "moka",
        userName: "Ayşe B.",
        rating: 4,
        comment: "Abonelik yönetimi için biçilmiş kaftan. Raporlama paneli çok detaylı.",
        date: "2026-01-05",
    },
];
